# Memory System Configuration Schema
[memory.schema]
version = "1.0"
description = """
Memory system configuration that defines:
1. Automatic memory management behaviors
2. File structure and organization
3. Command and tag processing rules
"""

[memory.behaviors]
hashtags = { 
  enabled = true,
  description = "When enabled, monitors conversations for #tags and maintains tag indices",
  storage = ".memory/indices/tags.md",
  update_frequency = "realtime"
}

[memory.commands]
decision = {
  prefix = "@decision",
  template = "## {timestamp}\n{content}\n\nContext: {context}\nImpact: {impact}",
  storage = ".memory/core/decisions.md"
}
todo = {
  prefix = "@todo",
  template = "- [ ] {content}\n  Added: {timestamp}",
  storage = ".memory/core/todos.md"
}
next = {
  prefix = "@next",
  template = "## Next Steps ({timestamp})\n{content}",
  storage = ".memory/core/next-steps.md"
}
memory = {
  prefix = "@memory",
  template = "## {timestamp}\n{content}\n\nTags: {tags}",
  storage = ".memory/core/memories.md"
}
milestone = {
  prefix = "@milestone",
  template = "## {timestamp} - {title}\n{content}\n\nImpact: {impact}",
  storage = ".memory/core/milestones.md"
}

[session.behaviors]
load_tarsx_syntax = {
  files = [
    ".tars/tarsx-lang/syntax.md",
    ".tars/tarsx-lang/syntax.ebnf"
  ],
  frequency = "startup",
  required = true
}

[daily.format]
template = """# {date}

## Session Summary
{summary}

## Decisions
{decisions}

## Progress
{progress}

## Next Steps
{next_steps}

## Tags
{tags}
"""
